name: Pull Request Validation

# on:
#   pull_request:
#     branches: [ main, develop ]

jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests with coverage
      run: npm run test:coverage
      
    - name: Build application
      run: npm run build
      
    - name: Check build size
      run: |
        echo "Build completed successfully!"
        echo "Build artifacts:"
        ls -la dist/
        echo "Total build size:"
        du -sh dist/
        
    - name: Comment PR
      uses: actions/github-script@v8
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Get build info
          const buildPath = 'dist';
          const buildSize = require('child_process')
            .execSync(`du -sh ${buildPath}`)
            .toString()
            .split('\t')[0];
            
          const comment = `## 🚀 Build Validation Results
          
          ✅ **Tests**: All tests passed
          ✅ **Linting**: No issues found  
          ✅ **Build**: Successful
          📦 **Build Size**: ${buildSize}
          
          This pull request is ready for review!`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

